// Compile src/kernel.wat → src/wasm-kernel.ts (base64-embedded bytes). Run: npm run build:wasm
// wabt is a devDependency; the generated file is committed so plain `tsup` builds keep working.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import initWabt from "wabt";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const wat = readFileSync(join(root, "src/kernel.wat"), "utf8");
const wabt = await initWabt();
const mod = wabt.parseWat("kernel.wat", wat, { simd: true });
const { buffer } = mod.toBinary({ log: false });
mod.destroy();

// sanity: the module must instantiate and export mem + many
const inst = new WebAssembly.Instance(new WebAssembly.Module(buffer), {});
if (!(inst.exports.mem instanceof WebAssembly.Memory) || typeof inst.exports.many !== "function") {
  throw new Error("kernel exports missing");
}

const b64 = Buffer.from(buffer).toString("base64");
writeFileSync(
  join(root, "src/wasm-kernel.ts"),
  `// Generated by scripts/build-wasm.mjs from src/kernel.wat — do not edit by hand.\n` +
    `// ${buffer.length} bytes of wasm (f64x2 SIMD batch kernel).\n` +
    `export const WASM_B64 =\n  "${b64}";\n`
);
console.log(`wasm kernel: ${buffer.length} bytes → src/wasm-kernel.ts`);
